---
- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
  with_items:
      - apt-utils
      - git
      - rsync
      - libpq-dev
      - libcurl4-openssl-dev

- name: Install additional packages 
  apt:
    name: "{{ item.key }}={{ item.value.version }}"
  when: additional_packages
  with_dict: "{{ additional_packages }}"

- name: Install bundler 
  gem:
    name: bundler
    state: latest
    user_install: false

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: rsync -avh /tmp/railsapp/ /var/www/

- name: Install all gems
  bundler:
    state: present
    gemfile: "/var/www/Gemfile"
    user_install: false
