---
- name: ensure packages are installed
  apt:
    name: "{{ item }}"
  with_items:
      - git
      - rsync
      - libpq-dev
      - libcurl4-openssl-dev

- name: Install bundler 
  gem:
    name: bundler
    state: latest
    user_install: false

- name: Creating project_root directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ working_dir }}/current/tmp/pids"

- name: Copy all rails data
  synchronize:
    src: "/tmp/railsapp"
    dest: "{{ working_dir }}/current"
    owner: no
    times: no
    checksum: yes

- name: Install all gems
  bundler:
    state: present
    gemfile: "{{ working_dir }}/current/Gemfile"
    user_install: false
