---
- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
  with_items:
      - git
      - rsync
      - libpq-dev
      - libcurl4-openssl-dev

- name: Install additional packages 
  apt:
    name: "{{ item.key }}={{ item.version }}"
  when: additional_packages
  with_dict: "{{ additional_packages }}"

- name: Install bundler 
  gem:
    name: bundler
    state: latest
    user_install: false

- name: Creating project_root directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ working_dir }}/current/tmp/pids"

- name: Copy all rails data
  command: "rsync -au /tmp/railsapp/ {{ working_dir }}/current/"

- name: Install all gems
  bundler:
    state: present
    gemfile: "{{ working_dir }}/current/Gemfile"
    user_install: false
