---
- name: Ensure packages are installed
  apk:
    name: "{{ item }}"
    update_cache: yes
  with_items:
      - git
      - bash
      - curl
      - rsync
      - tzdata
      - libcurl
      - build-base
      - postgresql-dev
      - linux-headers
      - nodejs
      
- name: Install additional packages 
  apk:
    name: "{{ item }}"
  when: additional_packages
  with_items: "{{ additional_packages }}"
  
- name: Update ruby-build
  command: cd /usr/local/rbenv/plugins/ruby-build && git pull && cd -
  
- name: Install ruby version
  command: rbenv install --verbose "{{ ruby_version }}"

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Clean migrations and .tags
  file:
    state: absent
    path:
  with_items:
    -  /var/cache/apk/
    - /var/www/db/migrate/

- name: Copy all node data
  command: rsync -auvh --delete --chown=root:root /tmp/railsapp/ /var/www/ --exclude vendor/bundle

- name: Install all gems
  bundler:
    state: present
    gemfile: "/var/www/Gemfile"
    deployment_mode: yes
    clean: yes
    extra_args: "--without development test"
    executable: "/usr/local/bin/bundle"

- name: Remove unnecessary packages
  apk:
    name: "{{ item }}"
    state: absent
  with_items:
      - git
      - rsync
      - build-base
