---
- name: Install gems
  gem:
    name: "{{ item.key }}"
    state: "{{ item.version }}"
    user_install: False
  with_dict: "{{ gems }}"

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: cp -r /tmp/railsapp/ /var/www
