---
- name: Use root as Sandbox user for apt
  lineinfile:
    dest: /etc/apt/apt.conf.d/70debconf
    line: 'APT::Sandbox::User "root";'
    state: present

- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
  with_items:
      - apt-utils
      - git
      - rsync
      - libpq-dev
      - libcurl4-openssl-dev
      - libuv1

- name: Install additional packages 
  apt:
    name: "{{ item.key }}={{ item.value.version }}"
    force: yes
  when: additional_packages
  with_dict: "{{ additional_packages }}"

- name: Install bundler and whenever 
  gem:
    name: "{{ item }}"
    state: latest
    user_install: false
  with_items:
      - bundler
      - whenever

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Clean migrate path
  file:
    state: absent
    path: "/var/www/db/migrate/"

- name: Copy all node data
  command: rsync -auvh --delete --chown=root:root /tmp/railsapp/ /var/www/ --exclude /vendor

- name: Install all gems
  bundler:
    state: present
    gemfile: "/var/www/Gemfile"
    deployment_mode: yes
    clean: yes
