---
- name: Ensure packages are installed
  apk:
    name: "{{ item }}"
    update_cache: yes
  with_items:
      - git
      - curl
      - rsync
      - tzdata
      - libcurl
      - build-base
      - alpine-sdk
      - jemalloc-dev
      - postgresql-dev
      - linux-headers
      - libxslt-dev 
      - libffi-dev
      - nodejs
      
- name: Install additional packages 
  apk:
    name: "{{ item }}"
    update_cache: yes
  when: additional_packages
  with_items: "{{ additional_packages }}"
  
- name: Install ruby version
  shell: source ~/.rvm/scripts/rvm && rvm install "{{ ruby_version }}"
  args:
    executable: /bin/bash

- name: Symlink ruby
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
    force: yes
  with_items:
    - { src: "/root/.rvm/rubies/ruby-{{ ruby_version }}/bin/ruby", dest: "/usr/bin/ruby" }
    - { src: "/root/.rvm/rubies/ruby-{{ ruby_version }}/bin/gem", dest: "/usr/bin/gem" }
    - { src: "/root/.rvm/rubies/ruby-{{ ruby_version }}/bin/erb", dest: "/usr/bin/erb" }
    - { src: "/root/.rvm/rubies/ruby-{{ ruby_version }}/bin/irb", dest: "/usr/bin/irb" }
    - { src: "/root/.rvm/rubies/ruby-{{ ruby_version }}/bin/rake", dest: "/usr/bin/rake" }
  
- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: rsync -auvh --delete --chown=root:root /tmp/railsapp/ /var/www/ --exclude vendor/bundle
  
- name: Install Bundler
  gem:
    name: bundler
    state: present
    user_install: no

- name: Install all gems
  bundler:
    state: present
    gemfile: "/var/www/Gemfile"
    deployment_mode: yes
    clean: yes
    extra_args: "--without development test"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/bin"

- name: Remove unnecessary packages
  apk:
    name: "{{ item }}"
    state: absent
  with_items:
      - git
      - rsync
      - build-base
      - alpine-sdk
      - jemalloc-dev
      - linux-headers
      - libxslt-dev 
      - libffi-dev

- name: Clean migrations and apk
  file:
    state: absent
    path:
  with_items:
    - /var/cache/apk/
    - /var/www/db/migrate/
