---
#- name: Install gems
#  gem:
#    name: "{{ item.key }}"
#    version: "{{ item.value.version }}"
#    user_install: False
#  with_dict: "{{ gems }}"

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes

- name: ensure packages are installed
  apt:
    name: "{{item}}"
  with_items:
      - git
      - libpq-dev

- name: Install bundler 
  gem:
    name: bundler
    state: latest
    user_install: false

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: cp -r /tmp/railsapp/ /var/www

- name: Install all gems
  bundler:
    state: present
    gemfile: /var/www/railsapp/Gemfile
    user_install: false
