---
- gem:
    name: unicorn
    state: latest
    user_install: False

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: cp -r /tmp/railsapp/ /var/www
