---
#- name: Install gems
#  gem:
#    name: "{{ item.key }}"
#    version: "{{ item.value.version }}"
#    user_install: False
#  with_dict: "{{ gems }}"

- name: Install bundler 
  gem:
    name: bundler
    version: 1.15.2 
    user_install: false

- name: Creating project_root directory
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Copy all node data
  command: cp -r /tmp/railsapp/ /var/www

- name: Install all gems
  bundler:
    state: present
    gemfile: /var/www/railsapp/Gemfile
    user_install: false
